theme: jekyll-theme-minimal


title:  BBYP Limited # [The title of your site]
description:  BBYP Limited is an investment management and consulting company that focuses on investments in marketable securities, Venture Capital and Private Equity asset classes. BBYP Limited also provides advisory services to support M&A transactions with IT start-ups based in Israel, Cyprus and Easter Europe.
 # [A short description of your site's purpose]

google_analytics: # [Your Google Analytics tracking ID]

github:
  is_project_page: false
  is_user_page: false
  
